<?php
/** Approved site-wide media-layout specification for the EHPMI dev site. */

return array(
    'version' => '2026-09-01-v2',
    'base_version' => '2026-09-01-v1',
    'post_ids' => array(
        23, 25, 327, 347, 355, 362, 374, 378, 558, 647, 656, 717, 803, 811,
        821, 832, 857, 892, 1039, 1061, 1073, 1113, 1420, 1524, 1545, 1676,
        1694, 1731, 1733, 1770, 1858, 1873, 1888, 1899, 1953, 1988, 2004,
        2028, 2058, 2075, 2310, 2329, 2333, 2355,
    ),
    'attachment_alts' => array(
        229 => 'EHPMI team members inspecting an environmental field site.',
        228 => 'EHPMI team members discussing conditions during a field visit.',
        320 => 'EHPMI organizational chart showing the founders board, president, programme directors and country coordinators.',
        844 => 'Forested mountain valley in Kyrgyzstan.',
        843 => 'Shore of Issyk-Kul Lake with mountains in the distance.',
        841 => 'Bishkek cityscape with snow-capped mountains in the distance.',
        842 => 'Panoramic view of Issyk-Kul Lake and the surrounding mountains.',
        624 => 'Horses and a foal grazing on the Mongolian steppe.',
        625 => 'Camel rider crossing the Mongolian steppe.',
        629 => 'Mountain river running through a valley in Tajikistan.',
        628 => 'Mountain lake surrounded by rocky peaks in Tajikistan.',
        586 => 'Children playing near the entrance of the church in Akhtala.',
        588 => 'Children posing in front of the church in Akhtala.',
        589 => 'Project team discussing the lead-remediation site near the church in Akhtala.',
        583 => 'Worker collecting a soil sample near a waste mound in Akhtala.',
        596 => 'Geotextile laid over remediated ground beside the church in Akhtala.',
        587 => 'Excavator spreading clean soil over geotextile in Akhtala.',
        585 => 'Dump truck unloading clean soil near the church in Akhtala.',
        584 => 'Workers preparing the remediated church grounds for planting in Akhtala.',
        595 => 'Project team discussing remediation work in Akhtala.',
        594 => 'Completed paved walkway leading to the church in Akhtala.',
        590 => 'Field staff inspecting and measuring soil at the Akhtala project site.',
        592 => 'Project team group portrait at the church ruins in Akhtala.',
        660 => 'Mountain agricultural landscape in Azerbaijan.',
        659 => 'Goitered gazelle standing in shallow water in Azerbaijan.',
        735 => 'Children beside an environmental education display at a school in Sovetskoe.',
        724 => 'Lead-contaminated industrial and tailings landscape near Sovetskoe.',
        731 => 'Pile of clean replacement soil beside homes in Sovetskoe.',
        736 => 'Workers excavating and replacing contaminated soil beside a house in Sovetskoe.',
        729 => 'Dump truck transporting soil through Sovetskoe village.',
        726 => 'Residents and children in a remediated yard in Sovetskoe.',
        1186 => 'Map of lead concentrations in topsoil in Sovetskoe before remediation.',
        1187 => 'Map of lead concentrations in topsoil in Sovetskoe after remediation.',
        723 => 'Educator leading an environmental health activity with children in a kindergarten.',
        721 => 'Children taking part in a classroom event in Sovetskoe.',
        730 => 'Community members attending a lead-risk meeting in Sovetskoe.',
        725 => 'Women attending a community meeting on lead exposure risks.',
        728 => 'Health worker taking a blood sample from a child.',
        739 => 'Laboratory worker processing blood samples for lead analysis.',
        720 => 'Parents and children during a health consultation in Sovetskoe.',
        719 => 'Medical and project team group portrait in Kyrgyzstan.',
        804 => 'Annotated map of the obsolete-pesticide burial site in Kochkor, Kyrgyzstan.',
        806 => 'Excavation pit at the obsolete-pesticide burial site in Kochkor.',
        805 => 'Mountain landscape around the obsolete-pesticide burial site in Kochkor.',
        807 => 'Field photographs documenting the waste trench and buried material at the Kochkor site.',
        814 => 'Annotated aerial view of the tailings site in Sumsar, Kyrgyzstan.',
        815 => 'Eroded bank of the tailings deposit in Sumsar.',
        816 => 'Drainage valley affected by contamination from the Sumsar tailings.',
        817 => 'Comparison photographs of the Sumsar site before and during remediation work.',
        818 => 'Map of lead contamination around the Sumsar tailings site.',
        823 => 'Muddy river water in Mailuu-Suu, Kyrgyzstan.',
        824 => 'Radiation detector measuring contamination on the ground in Mailuu-Suu.',
        825 => 'Map of uranium concentrations in drinking-water sources in Mailuu-Suu.',
        827 => 'Container housing a water-treatment system at a school in Mailuu-Suu.',
        826 => 'Technical map of the drinking-water treatment project in Mailuu-Suu.',
        833 => 'Lead smelter and nearby residential area in Shymkent.',
        834 => 'Field worker collecting a soil sample in Shymkent.',
        2212 => 'Map of lead concentrations in soil around Shymkent, Kazakhstan.',
        864 => 'Soil-sampling pit at the obsolete-pesticide burial site in Sherobod.',
        865 => 'Field workers collecting soil samples at the Sherobod site.',
        866 => 'Map of pesticide contamination at the Sherobod burial site.',
        877 => 'Worker wearing protective equipment during the Sherobod cleanup.',
        869 => 'Excavator lifting bags of contaminated material at the Sherobod site.',
        871 => 'Dump truck used during cleanup of the Sherobod pesticide burial site.',
        870 => 'Workers inside the excavation at the Sherobod cleanup site.',
        873 => 'Maps comparing the Sherobod site before and after cleanup.',
        898 => 'Map of lead concentrations at the Kutaisi riverside site.',
        897 => 'Map of arsenic concentrations at the Kutaisi riverside site.',
        896 => 'Map of mercury concentrations at the Kutaisi riverside site.',
        1323 => 'Overgrown riverside site in Kutaisi before cleanup.',
        899 => 'Cleared riverside site in Kutaisi after cleanup work.',
        2286 => 'Gloved hand holding a labelled contaminated-soil sample at the Darkat site.',
        1259 => 'Children outside a kindergarten in the Rudnaya River Valley.',
        1253 => 'Map of lead contamination in soil in Rudnaya Pristan.',
        1255 => 'Field worker collecting a water sample in Rudnaya Pristan.',
        1260 => 'Contaminated tailings landscape in the Rudnaya River Valley.',
        1254 => 'Soil remediation work at a kindergarten playground in Serzhantovo.',
        1258 => 'Loader handling lead concentrate near a playground in Rudnaya Pristan.',
        1257 => 'Community lecture on reducing lead exposure in the Rudnaya River Valley.',
        1256 => 'Remediated schoolyard in the Rudnaya River Valley.',
        1261 => 'Child undergoing a blood lead test in the Rudnaya River Valley.',
        1252 => 'Chart showing declining mean blood lead levels from 2007 to 2009.',
        1547 => 'Access road and contaminated industrial site before cleanup in Sumgait.',
        1677 => 'Speaker presenting a waste-management strategy at Khazar University.',
        1892 => 'Participants at a food-safety awareness meeting in Georgia.',
        1963 => 'Training participants discussing a field-assessment exercise in Kazakhstan.',
        1976 => 'Trainees wearing protective suits for contaminated-site fieldwork.',
        1975 => 'Protective equipment prepared for contaminated-site fieldwork.',
        1973 => 'Participants holding certificates after contaminated-site assessment training.',
        1972 => 'Group portrait of contaminated-site assessment training participants.',
        1971 => 'Participants inspecting a contaminated-site field location in Kazakhstan.',
        1970 => 'Field team collecting and reviewing a sample at a contaminated site.',
        1969 => 'Two field researchers wearing protective shoe covers at an assessment site.',
        1968 => 'Researcher recording environmental sample data during fieldwork.',
        1967 => 'Labelled environmental sample bag held by a gloved researcher.',
        1966 => 'Field assessment team group portrait in Kazakhstan.',
        1965 => 'Map of sites assessed in Kazakhstan in 2023.',
        2005 => 'Project staff providing protective equipment to a resident before the DDT cleanup.',
        2017 => 'Project worker interviewing a resident before cleanup of the DDT burial site.',
        2016 => 'Resident completing a project questionnaire before the DDT cleanup.',
        2013 => 'Workers hand-excavating the DDT burial site in Settlement Number 1.',
        2012 => 'Sampling and safety equipment beside the DDT excavation.',
        2007 => 'Two project staff members at the DDT cleanup site.',
        2078 => 'Audience attending a presentation on blood lead levels in preschool children.',
        2312 => 'Field team collecting soil samples at the contaminated site in Kutaisi.',
        2311 => 'Field team reviewing a sample near industrial ruins in Kutaisi.',
        2334 => 'Participants at the Astana workshop on lead poisoning in children.',
        2352 => 'EHPMI Annual Workshop 2026 participants by Issyk-Kul Lake in Cholpon-Ata.',
        2349 => 'EHPMI workshop participants taking a tea break in a yurt.',
        2354 => 'EHPMI Annual Workshop 2026 session inside a yurt venue.',
        2351 => 'Participants discussing workshop topics in the yurt venue.',
        2350 => 'EHPMI workshop group discussion inside the yurt venue.',
    ),
    'attachment_alt_sync' => array(
        895 => 'The soil base consists of slag, alluvial gravel, and sandy and silty loam',
        894 => 'The area is flat with a slight slope northeast towards the Rioni River',
        1548 => 'Wastewater settling pond at the pumping station, Sumgait contamination, POPs',
        1549 => 'Wastes at the site before remediation',
        1550 => 'Settling pond of oily organic sludge',
        1551 => 'collecting a water sample at the site in 2014',
        1552 => 'Concentrations of benzo(a)pyrene before remediation, Azerikimya, EHPMI',
        1553 => 'Concentrations of benzene before remediation, Azerikimya, EHPMI',
        1554 => 'Concentrations of PCB before remediation, Azerikimya, EHPMI',
        1555 => 'clean soil in the remediated area',
        1556 => 'Bulldozer leveling the clean soil',
        1557 => 'Trees planted in the spring 2015 in Sumgait',
        1558 => 'Trees planted in the spring 2015 in Sumgait',
        1559 => 'Arbor in central part of the site',
        1560 => 'Members of the project team in the remediated area',
        1561 => 'EHPMI, MENR, The state Oil company of Azerbaijan (SOCAR)',
        1562 => 'EHPMI, MENR, The state Oil company of Azerbaijan (SOCAR)',
        1563 => 'EHPMI, MENR, The state Oil company of Azerbaijan (SOCAR)',
        1564 => 'EHPMI, MENR, The state Oil company of Azerbaijan (SOCAR)',
        1565 => 'EHPMI, MENR, The state Oil company of Azerbaijan (SOCAR)',
        1716 => 'The project on Disaster Risk final workshop',
        1717 => 'The project on Disaster Risk final workshop',
    ),
    'expected_previous_attachment_alts' => array(
        1976 => 'Theoretical part of the training',
    ),
    'media_text_alts' => array(
        231 => 'Kindergarten educators in animal costumes performing with children.',
        350 => 'Black Sea coast viewed from a wooded hillside in Georgia.',
        626 => 'Partly frozen stream in a mountain landscape in Mongolia.',
        593 => 'Map of lead concentrations in soil in the Akhtala monastery yard.',
        661 => 'Oil-contaminated water and shoreline in Azerbaijan.',
        733 => 'Water-treatment and storage system installed in Sovetskoe.',
        734 => 'Children holding educational leaflets about lead exposure risks in Sovetskoe.',
        718 => 'Local officials inspecting remediated soil in Sovetskoe.',
        740 => 'Chart of children with blood lead concentrations above 10 micrograms per decilitre in 2016, 2017 and 2019.',
        813 => 'View of Sumsar town and the surrounding mountains.',
        822 => 'Mailuu-Suu town square with mountains in the background.',
        828 => 'Health worker seated with a child during a project visit in Mailuu-Suu.',
        829 => 'Project team and community members discussing field conditions in Mailuu-Suu.',
        835 => 'Children near School Number 49 in Shymkent with an industrial stack in the background.',
        2299 => 'Child beside damaged ground near the contaminated site in Sherobod.',
        872 => 'Community members reviewing pesticide-safety information in Jami district.',
        2313 => 'Kutaisi contaminated-site field assessment team group portrait.',
    ),
    'expected_previous_media_attachment_alts' => array(
        2313 => '2025_12_21_Kutaisi_Litafoni-2',
    ),
    'featured_alts' => array(
        591 => 'Akhtala monastery and its remediated grounds in Armenia.',
        744 => 'School entrance during a community event in Sovetskoe, Kyrgyzstan.',
        902 => 'Cleared contaminated riverside area in Kutaisi after remediation.',
        1086 => 'Workers packing contaminated pesticide waste into bulk bags at the Darkat cleanup site.',
        1698 => 'Speaker at the final disaster-risk management workshop in Mongolia.',
        1995 => 'Sheep in a livestock enclosure at a site assessed for pesticide contamination in Tajikistan.',
    ),
    'legacy_alts' => array(
        327 => array(
            '/wp-content/uploads/2022/11/DSC02468_2000-650x433.jpg' => 'Historic stone tower in a mountainous industrial landscape in Armenia.',
            '/wp-content/uploads/2022/11/DSC08705-650x433.jpg' => 'Mining town and mountain landscape in Armenia.',
        ),
        347 => array('/wp-content/uploads/2022/12/Georgia-1320x672.jpg' => 'Map of Georgia.'),
        355 => array(
            '/wp-content/uploads/2022/11/Kazakhstan-1320x500.jpg' => 'Map of Kazakhstan.',
            '/wp-content/uploads/2022/11/air_pollution-650x488.jpg' => 'Industrial smokestacks beside an urban street in Kazakhstan.',
            '/wp-content/uploads/2022/11/air_pollution2-650x488.jpg' => 'Apartment buildings affected by industrial air pollution in Kazakhstan.',
        ),
        362 => array('/wp-content/uploads/2023/02/Kyrgyzstan-1320x610.jpg' => 'Map of Kyrgyzstan.'),
        374 => array('/wp-content/uploads/2022/12/Mongolia-1320x505.jpg' => 'Map of Mongolia.'),
        378 => array(
            '/wp-content/uploads/2022/11/Tajikistan-1320x767.jpg' => 'Map of Tajikistan.',
            '/wp-content/uploads/2022/11/02_xrf_ludmila_umed_bek_said.jpg' => 'Field team using an X-ray fluorescence analyzer inside an industrial building in Tajikistan.',
        ),
        647 => array('/wp-content/uploads/2022/12/Ukraine-1320x767.jpg' => 'Map of Ukraine.'),
        656 => array('/wp-content/uploads/2022/11/Azerbaijan-1320x703.jpg' => 'Map of Azerbaijan.'),
    ),
    'pair_styles' => array(
        23 => array(array('229,228', 'is-style-ehpmi-photo-pair-3x2')),
        327 => array(array('0,0', 'is-style-ehpmi-photo-pair-3x2')),
        355 => array(array('0,0', 'is-style-ehpmi-photo-pair-4x3')),
        362 => array(array('844,843', 'is-style-ehpmi-photo-pair-3x2'), array('841,842', 'is-style-ehpmi-photo-pair-3x2')),
        374 => array(array('624,625', 'is-style-ehpmi-photo-pair-3x2')),
        378 => array(array('629,628', 'is-style-ehpmi-photo-pair-3x2')),
        558 => array(
            array('586,588', 'is-style-ehpmi-photo-pair-4x3'), array('589,583', 'is-style-ehpmi-photo-pair-4x3'),
            array('596,587', 'is-style-ehpmi-photo-pair-4x3'), array('585,584', 'is-style-ehpmi-photo-pair-4x3'),
            array('595,594', 'is-style-ehpmi-photo-pair-4x3'), array('590,592', 'is-style-ehpmi-photo-pair-3x2'),
        ),
        656 => array(array('660,659', 'is-style-ehpmi-photo-pair-3x2')),
        717 => array(
            array('735,724', 'is-style-ehpmi-photo-pair-3x2'), array('731,736', 'is-style-ehpmi-photo-pair-3x2'),
            array('729,726', 'is-style-ehpmi-photo-pair-3x2'), array('1186,1187', 'is-style-ehpmi-photo-pair-4x3'),
            array('723,721', 'is-style-ehpmi-photo-pair-3x2'), array('730,725', 'is-style-ehpmi-photo-pair-3x2'),
            array('728,739', 'is-style-ehpmi-photo-pair-3x2'), array('720,719', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        803 => array(array('806,805', 'is-style-ehpmi-photo-pair-4x3')),
        811 => array(array('815,816', 'is-style-ehpmi-photo-pair-3x2')),
        821 => array(array('823,824', 'is-style-ehpmi-photo-pair-4x3'), array('827,826', 'is-style-ehpmi-photo-pair-3x4')),
        832 => array(array('833,834', 'is-style-ehpmi-photo-pair-4x3')),
        857 => array(
            array('864,865', 'is-style-ehpmi-photo-pair-3x2'), array('877,869', 'is-style-ehpmi-photo-pair-3x2'),
            array('871,870', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        892 => array(array('895,894', 'is-style-ehpmi-photo-pair-3x2'), array('1323,899', 'is-style-ehpmi-photo-pair-3x2')),
        1039 => array(array('1042,1044', 'is-style-ehpmi-photo-pair-3x2'), array('1043,1041', 'is-style-ehpmi-photo-pair-4x3')),
        1061 => array(array('1065,1066', 'is-style-ehpmi-photo-pair-3x2'), array('1064,1060', 'is-style-ehpmi-photo-pair-3x2')),
        1073 => array(
            array('2286,1071', 'is-style-ehpmi-photo-pair-3x4'), array('1081,1079', 'is-style-ehpmi-photo-pair-3x2'),
            array('1080,1074', 'is-style-ehpmi-photo-pair-3x2'), array('1077,1078', 'is-style-ehpmi-photo-pair-3x4'),
        ),
        1113 => array(
            array('1259,1253', 'is-style-ehpmi-photo-pair-4x3'), array('1255,1260', 'is-style-ehpmi-photo-pair-4x3'),
            array('1254,1258', 'is-style-ehpmi-photo-pair-4x3'), array('1257,1256', 'is-style-ehpmi-photo-pair-4x3'),
            array('1261,1252', 'is-style-ehpmi-photo-pair-3x2'),
        ),
        1420 => array(
            array('1422,1423', 'is-style-ehpmi-photo-pair-3x2'), array('1424,1425', 'is-style-ehpmi-photo-pair-4x3'),
            array('1426,1427', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        1545 => array(
            array('1548,1549', 'is-style-ehpmi-photo-pair-4x3'), array('1550,1551', 'is-style-ehpmi-photo-pair-4x3'),
            array('1555,1556', 'is-style-ehpmi-photo-pair-3x2'), array('1557,1558', 'is-style-ehpmi-photo-pair-4x3'),
            array('1559,1560', 'is-style-ehpmi-photo-pair-4x3'), array('1564,1565', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        1694 => array(array('1716,1717', 'is-style-ehpmi-photo-pair-4x3')),
        1733 => array(
            array('1788,1794', 'is-style-ehpmi-photo-pair-3x4'), array('1791,1798', 'is-style-ehpmi-photo-pair-4x3'),
            array('1797,1790', 'is-style-ehpmi-photo-pair-4x3'), array('1792,1789', 'is-style-ehpmi-photo-pair-4x3'),
            array('1795,1787', 'is-style-ehpmi-photo-pair-4x3'), array('1793,1796', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        1770 => array(array('1778,1777', 'is-style-ehpmi-photo-pair-4x3'), array('1773,1772', 'is-style-ehpmi-photo-pair-4x3')),
        1858 => array(array('1859,1860', 'is-style-ehpmi-photo-pair-3x2'), array('1861,1862', 'is-style-ehpmi-photo-pair-3x2')),
        1953 => array(
            array('1963,1976', 'is-style-ehpmi-photo-pair-4x3'), array('1975,1974', 'is-style-ehpmi-photo-pair-4x3'),
            array('1973,1972', 'is-style-ehpmi-photo-pair-4x3'), array('1971,1970', 'is-style-ehpmi-photo-pair-4x3'),
        ),
        2004 => array(
            array('2017,2016', 'is-style-ehpmi-photo-pair-3x4'), array('2015,2014', 'is-style-ehpmi-photo-pair-3x2'),
            array('2013,2012', 'is-style-ehpmi-photo-pair-3x4'), array('2011,2010', 'is-style-ehpmi-photo-pair-3x2'),
            array('2009,2008', 'is-style-ehpmi-photo-pair-3x2'), array('2007,2006', 'is-style-ehpmi-photo-pair-3x4'),
        ),
        2028 => array(array('2030,2031', 'is-style-ehpmi-photo-pair-3x2'), array('2033,2049', 'is-style-ehpmi-photo-pair-3x2')),
        2075 => array(array('2078,2077', 'is-style-ehpmi-photo-pair-3x2')),
        2310 => array(array('2312,2311', 'is-style-ehpmi-photo-pair-3x4')),
        2329 => array(array('2341,2331', 'is-style-ehpmi-photo-pair-3x2')),
        2333 => array(array('2334,2335', 'is-style-ehpmi-photo-pair-3x2')),
    ),
    'wide_attachment_ids' => array(
        320, 675, 804, 807, 814, 817, 818, 825, 2212, 866, 873,
        1909, 1908, 1907, 1906, 1905, 1904, 1903,
        1965, 1964, 1992, 1993, 1994,
    ),
    'wide_legacy_paths' => array(
        347 => array('/wp-content/uploads/2022/12/Georgia-1320x672.jpg'),
        355 => array('/wp-content/uploads/2022/11/Kazakhstan-1320x500.jpg'),
        362 => array('/wp-content/uploads/2023/02/Kyrgyzstan-1320x610.jpg'),
        374 => array('/wp-content/uploads/2022/12/Mongolia-1320x505.jpg'),
        378 => array('/wp-content/uploads/2022/11/Tajikistan-1320x767.jpg'),
        647 => array('/wp-content/uploads/2022/12/Ukraine-1320x767.jpg'),
        656 => array('/wp-content/uploads/2022/11/Azerbaijan-1320x703.jpg'),
    ),
);
